# Generated by Django 5.1.15 on 2026-07-16 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=80, unique=True)),
                ('base', models.CharField(choices=[('default', 'Default'), ('soft', 'Soft'), ('sharp', 'Sharp'), ('mono', 'Mono')], default='default', help_text='Built-in preset the token overrides are layered on.', max_length=20)),
                ('tokens', models.JSONField(default=dict)),
                ('is_published', models.BooleanField(default=True, help_text='Visible to test users in the theme selector.')),
                ('created_by', models.CharField(blank=True, max_length=150)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
