# Generated by Django 5.1.15 on 2026-07-21 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('themes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='theme',
            name='country_scheme',
            field=models.CharField(blank=True, choices=[('vibrant', 'Vibrant'), ('greens', 'Greens'), ('browns', 'Browns'), ('uniform', 'Uniform'), ('blues', 'Blues'), ('purples', 'Purples'), ('greys', 'Greys')], default='', help_text='Country color scheme (js/features/color-schemes.js). Empty = default.', max_length=16),
        ),
        migrations.AddField(
            model_name='theme',
            name='ocean_color',
            field=models.CharField(blank=True, default='', help_text='Ocean/water color (hex/rgb). Empty = default.', max_length=32),
        ),
        migrations.AddField(
            model_name='theme',
            name='scene_bg',
            field=models.CharField(blank=True, default='', help_text='Space color behind the globe (hex/rgb). Empty = default.', max_length=32),
        ),
    ]
