"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=''):
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-t7u@c$-xxr+5!e9yi2jfh)t!2h!76@$2!d2fh@t5idekm9&04e',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')

# In DEBUG, accept any Host so the dev server (bound to 0.0.0.0) is reachable
# over the LAN by IP or hostname — e.g. testing the globe on a phone. Production
# runs with DEBUG off and the explicit DJANGO_ALLOWED_HOSTS allow-list above.
if DEBUG:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Local
    'geo',
    'players',
    'quiz',
    'stats',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static (admin + stats/ dashboards) straight from gunicorn
    # so DEBUG=False deployments don't need a separate static host. Immediately
    # after SecurityMiddleware per WhiteNoise's documented placement.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Driven by DATABASE_URL when set (e.g. postgres://user:pass@host:5432/db in
# production); falls back to the local SQLite file so dev needs no env at all.
# conn_max_age keeps connections open across requests (cheap reuse under load);
# conn_health_checks revalidates a pooled connection before use.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        conn_health_checks=True,
    )
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# `collectstatic` gathers admin + DRF + stats assets here; WhiteNoise serves them
# with hashed, far-future-cacheable filenames in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Django REST Framework -------------------------------------------------
# The public quiz API is token-light: players are identified by an opaque
# device token sent in the X-Device-Token header (see players.auth). There is
# no session/login for end users; the only "real" auth is staff login for the
# admin + owner stats pages.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
    'UNAUTHENTICATED_USER': None,
}


# --- CORS ------------------------------------------------------------------
# The static frontend is served from a different origin (Cloudflare in prod, a
# local static server in dev) and calls this API cross-origin. In production,
# allow-list the exact frontend origin(s) via CORS_ALLOWED_ORIGINS. In DEBUG we
# additionally allow loopback, 0.0.0.0, mDNS `*.local`, and private-LAN IPv4
# origins on any port, so the frontend's dev port (8001, 5500, …) and LAN access
# (e.g. from a phone) just work without hardcoding the origin here.
CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000')
CORS_ALLOW_HEADERS = ('accept', 'content-type', 'x-device-token')
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r'^http://(localhost|127\.0\.0\.1|0\.0\.0\.0|\[::1\])(:\d+)?$',
        r'^http://[a-zA-Z0-9-]+\.local(:\d+)?$',
        r'^http://10\.\d{1,3}\.\d{1,3}\.\d{1,3}(:\d+)?$',
        r'^http://192\.168\.\d{1,3}\.\d{1,3}(:\d+)?$',
        r'^http://172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}(:\d+)?$',
    ]


# --- CSRF ------------------------------------------------------------------
CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS', '')


# --- Daily quiz tuning -----------------------------------------------------
# Number of questions in a daily challenge, and the per-question client-time
# clamp (ms) used to blunt obvious timing spoofs.
DAILY_QUIZ_QUESTION_COUNT = int(os.environ.get('DAILY_QUIZ_QUESTION_COUNT', '10'))
ANSWER_MIN_MS = int(os.environ.get('ANSWER_MIN_MS', '250'))
ANSWER_MAX_MS = int(os.environ.get('ANSWER_MAX_MS', '120000'))
# A finished run's reported total time is floored at this fraction of the real
# server-observed wall-clock (start->finish), to blunt obvious timing spoofs.
ANSWER_WALLCLOCK_MIN_RATIO = float(os.environ.get('ANSWER_WALLCLOCK_MIN_RATIO', '0.5'))
# Minimum land area (km²) for a country to be a target/clickable in map-click
# (region-click) questions — smaller countries are too tiny to tap on the globe.
QUIZ_MIN_CLICK_AREA_KM2 = float(os.environ.get('QUIZ_MIN_CLICK_AREA_KM2', '5000'))


# --- Caching ---------------------------------------------------------------
# Redis in production (REDIS_URL, e.g. redis://127.0.0.1:6379/0); in-process
# locmem otherwise so dev and tests need no Redis. The daily leaderboard is the
# main beneficiary — see quiz/services.leaderboard().
REDIS_URL = os.environ.get('REDIS_URL', '')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'},
            'KEY_PREFIX': 'globe3d',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'globe3d-locmem',
        }
    }


# --- Production security ----------------------------------------------------
# Engaged only with DEBUG off. nginx terminates TLS and forwards the original
# scheme via X-Forwarded-Proto, so Django must trust that header to know a
# request arrived over HTTPS. nginx (not Django) does the HTTP->HTTPS redirect.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# --- Stripe (later milestone; unused in v1) --------------------------------
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')
