"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.1.15.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

import dj_database_url
from dotenv import load_dotenv

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Load backend/.env into the environment if present, before anything below reads
# os.environ. Real environment variables still win (override defaults to False),
# and a missing file is a no-op — so dev with no .env and tests are unaffected.
load_dotenv(BASE_DIR / '.env')


def _env_bool(name, default=False):
    return os.environ.get(name, str(default)).lower() in ('1', 'true', 'yes', 'on')


def _env_list(name, default=''):
    raw = os.environ.get(name, default)
    return [item.strip() for item in raw.split(',') if item.strip()]


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get(
    'DJANGO_SECRET_KEY',
    'django-insecure-t7u@c$-xxr+5!e9yi2jfh)t!2h!76@$2!d2fh@t5idekm9&04e',
)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = _env_bool('DJANGO_DEBUG', True)

ALLOWED_HOSTS = _env_list('DJANGO_ALLOWED_HOSTS', 'localhost,127.0.0.1')

# In DEBUG, accept any Host so the dev server (bound to 0.0.0.0) is reachable
# over the LAN by IP or hostname — e.g. testing the globe on a phone. Production
# runs with DEBUG off and the explicit DJANGO_ALLOWED_HOSTS allow-list above.
if DEBUG:
    ALLOWED_HOSTS = ['*']


# Application definition

INSTALLED_APPS = [
    # Metrics: registers the Prometheus collectors + model/migration hooks. First
    # so its app-registry hooks are in place before the local apps load.
    'django_prometheus',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    # Third-party
    'rest_framework',
    'corsheaders',
    # Local
    'geo',
    'players',
    'quiz',
    'stats',
    'themes',
]

MIDDLEWARE = [
    # Prometheus request timing: Before must be FIRST and After LAST so the
    # `..._including_middlewares` latency histogram spans the whole stack below.
    'django_prometheus.middleware.PrometheusBeforeMiddleware',
    'django.middleware.security.SecurityMiddleware',
    # Serves collected static (admin + stats/ dashboards) straight from gunicorn
    # so DEBUG=False deployments don't need a separate static host. Immediately
    # after SecurityMiddleware per WhiteNoise's documented placement.
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'corsheaders.middleware.CorsMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django_prometheus.middleware.PrometheusAfterMiddleware',
]

ROOT_URLCONF = 'config.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'config.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# Driven by DATABASE_URL when set (e.g. postgres://user:pass@host:5432/db in
# production); falls back to the local SQLite file so dev needs no env at all.
# conn_max_age keeps connections open across requests (cheap reuse under load);
# conn_health_checks revalidates a pooled connection before use.
DATABASES = {
    'default': dj_database_url.config(
        default=f'sqlite:///{BASE_DIR / "db.sqlite3"}',
        conn_max_age=int(os.environ.get('DB_CONN_MAX_AGE', '60')),
        conn_health_checks=True,
    )
}

# Swap the DB backend for django-prometheus's instrumented subclass so query and
# connection counts/latency are exported. Keyed off whatever engine dj_database_url
# picked (Postgres in prod, SQLite in dev), so it stays env-driven; an unrecognised
# engine is left untouched rather than crashing. The wrappers subclass the stock
# Django backends, so psycopg3 under Django 5.1 works unchanged.
_PROM_DB_ENGINES = {
    'django.db.backends.postgresql': 'django_prometheus.db.backends.postgresql',
    'django.db.backends.postgresql_psycopg2': 'django_prometheus.db.backends.postgresql',
    'django.db.backends.sqlite3': 'django_prometheus.db.backends.sqlite3',
}
_engine = DATABASES['default'].get('ENGINE')
if _engine in _PROM_DB_ENGINES:
    DATABASES['default']['ENGINE'] = _PROM_DB_ENGINES[_engine]


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = 'static/'
# `collectstatic` gathers admin + DRF + stats assets here; WhiteNoise serves them
# with hashed, far-future-cacheable filenames in production.
STATIC_ROOT = BASE_DIR / 'staticfiles'
STORAGES = {
    'default': {'BACKEND': 'django.core.files.storage.FileSystemStorage'},
    'staticfiles': {
        'BACKEND': 'whitenoise.storage.CompressedManifestStaticFilesStorage',
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


# --- Django REST Framework -------------------------------------------------
# The public quiz API is token-light: players are identified by an opaque
# device token sent in the X-Device-Token header (see players.auth). There is
# no session/login for end users; the only "real" auth is staff login for the
# admin + owner stats pages.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [],
    'DEFAULT_PERMISSION_CLASSES': [],
    'UNAUTHENTICATED_USER': None,
}


# --- CORS ------------------------------------------------------------------
# The static frontend is served from a different origin (Cloudflare in prod, a
# local static server in dev) and calls this API cross-origin. In production,
# allow-list the exact frontend origin(s) via CORS_ALLOWED_ORIGINS. In DEBUG we
# additionally allow loopback, 0.0.0.0, mDNS `*.local`, and private-LAN IPv4
# origins on any port, so the frontend's dev port (8001, 5500, …) and LAN access
# (e.g. from a phone) just work without hardcoding the origin here.
CORS_ALLOWED_ORIGINS = _env_list('CORS_ALLOWED_ORIGINS', 'http://localhost:8000,http://127.0.0.1:8000')
CORS_ALLOW_HEADERS = ('accept', 'content-type', 'x-device-token', 'x-audit-token')
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r'^http://(localhost|127\.0\.0\.1|0\.0\.0\.0|\[::1\])(:\d+)?$',
        r'^http://[a-zA-Z0-9-]+\.local(:\d+)?$',
        r'^http://10\.\d{1,3}\.\d{1,3}\.\d{1,3}(:\d+)?$',
        r'^http://192\.168\.\d{1,3}\.\d{1,3}(:\d+)?$',
        r'^http://172\.(1[6-9]|2\d|3[01])\.\d{1,3}\.\d{1,3}(:\d+)?$',
    ]


# --- CSRF ------------------------------------------------------------------
CSRF_TRUSTED_ORIGINS = _env_list('CSRF_TRUSTED_ORIGINS', '')


# --- Daily quiz tuning -----------------------------------------------------
# Number of questions in a daily challenge, and the per-question client-time
# clamp (ms) used to blunt obvious timing spoofs.
DAILY_QUIZ_QUESTION_COUNT = int(os.environ.get('DAILY_QUIZ_QUESTION_COUNT', '10'))
ANSWER_MIN_MS = int(os.environ.get('ANSWER_MIN_MS', '250'))
ANSWER_MAX_MS = int(os.environ.get('ANSWER_MAX_MS', '120000'))
# A finished run's reported total time is floored at this fraction of the real
# server-observed wall-clock (start->finish), to blunt obvious timing spoofs.
ANSWER_WALLCLOCK_MIN_RATIO = float(os.environ.get('ANSWER_WALLCLOCK_MIN_RATIO', '0.5'))
# Minimum land area (km²) for a country to be a target/clickable in map-click
# (region-click) questions — smaller countries are too tiny to tap on the globe.
QUIZ_MIN_CLICK_AREA_KM2 = float(os.environ.get('QUIZ_MIN_CLICK_AREA_KM2', '5000'))


# --- Daily-quiz audit tool ---------------------------------------------------
# Superuser-only audit mode: /audit/launch mints a signed token that the static
# frontend sends back as X-Audit-Token (see quiz.audit_auth). The launch page
# needs to know where the frontend lives to build the hand-off link.
AUDIT_TOKEN_MAX_AGE = int(os.environ.get('AUDIT_TOKEN_MAX_AGE', '3600'))  # 1h
# Where the launch page sends the freshly minted token. Explicit env var wins;
# otherwise in production fall back to the canonical frontend origin (the first
# CORS-allowed origin the operator already configures) rather than the dev
# default, so a missing AUDIT_FRONTEND_ORIGIN can't hand out a localhost link.
_default_audit_origin = (
    CORS_ALLOWED_ORIGINS[0] if (not DEBUG and CORS_ALLOWED_ORIGINS) else 'http://localhost:8001'
)
AUDIT_FRONTEND_ORIGIN = os.environ.get('AUDIT_FRONTEND_ORIGIN', _default_audit_origin)


# --- Caching ---------------------------------------------------------------
# Redis in production (REDIS_URL, e.g. redis://127.0.0.1:6379/0); in-process
# locmem otherwise so dev and tests need no Redis. The daily leaderboard is the
# main beneficiary — see quiz/services.leaderboard().
REDIS_URL = os.environ.get('REDIS_URL', '')
if REDIS_URL:
    CACHES = {
        'default': {
            'BACKEND': 'django_redis.cache.RedisCache',
            'LOCATION': REDIS_URL,
            'OPTIONS': {'CLIENT_CLASS': 'django_redis.client.DefaultClient'},
            'KEY_PREFIX': 'globe3d',
        }
    }
else:
    CACHES = {
        'default': {
            'BACKEND': 'django.core.cache.backends.locmem.LocMemCache',
            'LOCATION': 'globe3d-locmem',
        }
    }


# --- Production security ----------------------------------------------------
# Engaged only with DEBUG off. nginx terminates TLS and forwards the original
# scheme via X-Forwarded-Proto, so Django must trust that header to know a
# request arrived over HTTPS. nginx (not Django) does the HTTP->HTTPS redirect.
if not DEBUG:
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_HSTS_SECONDS = int(os.environ.get('SECURE_HSTS_SECONDS', '31536000'))
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'


# --- Stripe (later milestone; unused in v1) --------------------------------
STRIPE_SECRET_KEY = os.environ.get('STRIPE_SECRET_KEY', '')
STRIPE_WEBHOOK_SECRET = os.environ.get('STRIPE_WEBHOOK_SECRET', '')


# --- Monitoring: Prometheus metrics ----------------------------------------
# The remote Prometheus scrapes /metrics (via the IP-allowlisted metrics vhost —
# see deploy/monitoring/). Multiprocess aggregation across gunicorn workers is set
# up in deploy/gunicorn.conf.py + globe3d.service (PROMETHEUS_MULTIPROC_DIR).
# Skip the boot-time migration-state DB query per worker (postgres_exporter + CI
# cover migration drift); it would add a DB dependency to worker readiness.
PROMETHEUS_EXPORT_MIGRATIONS = False
# Latency histogram buckets tuned for a sub-second JSON API (the library default
# runs out to 25/50/75s, wasting series and giving coarse low-end resolution).
PROMETHEUS_LATENCY_BUCKETS = (
    0.005, 0.01, 0.025, 0.05, 0.1, 0.25, 0.5, 1.0, 2.5, 5.0, float('inf'),
)


# --- Monitoring: logging ---------------------------------------------------
# Django's default `console` handler is gated behind require_debug_true, so with
# DEBUG=False unhandled-exception (500) tracebacks never reach stdout — they only
# go to the (unconfigured) mail_admins handler and are effectively swallowed. This
# routes ERROR tracebacks to stdout -> gunicorn (foreground) -> journald. GlitchTip
# capture is handled independently by the Sentry SDK below (it hooks callHandlers,
# so it is unaffected by these loggers' propagate=False), so there is no Sentry
# handler here and no double-report.
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {name} {process:d}/{threadName} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console'],
        'level': 'INFO',
    },
    'loggers': {
        'django': {
            'handlers': ['console'],
            'level': os.environ.get('DJANGO_LOG_LEVEL', 'INFO'),
            'propagate': False,
        },
        # 500 tracebacks land here at ERROR (see comment above).
        'django.request': {
            'handlers': ['console'],
            'level': 'ERROR',
            'propagate': False,
        },
        # Never emit per-query SQL to journald.
        'django.db.backends': {
            'level': 'WARNING',
            'propagate': False,
        },
    },
}


# --- Monitoring: error tracking (GlitchTip via the Sentry SDK) --------------
# Enabled only when a DSN is present, so dev/tests (no DSN in .env) never phone
# home. The DSN lives in backend/.env (gitignored), never in source. GlitchTip is
# Sentry-ingest-compatible, so the standard sentry-sdk DjangoIntegration works.
SENTRY_DSN = os.environ.get('GLITCHTIP_DSN') or os.environ.get('SENTRY_DSN', '')
if SENTRY_DSN:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    from sentry_sdk.scrubber import DEFAULT_DENYLIST, EventScrubber
    from django.core.exceptions import DisallowedHost

    sentry_sdk.init(
        dsn=SENTRY_DSN,
        # Bots probe the origin's raw IP with a bogus Host header, so CommonMiddleware
        # raises DisallowedHost and returns 400 — the allow-list doing its job, not an
        # app fault. Without this, the Django integration reports every such probe to
        # GlitchTip as an error. Drop it (and only it) at the SDK. Do NOT "fix" this by
        # adding the IP to DJANGO_ALLOWED_HOSTS — that would serve the app on the bare
        # IP, which is exactly what the allow-list is there to prevent.
        ignore_errors=[DisallowedHost],
        integrations=[
            # Group issues/transactions by URL *pattern* so dynamic segments
            # (e.g. /api/daily/<date>/leaderboard) don't fan out.
            DjangoIntegration(transaction_style='url'),
        ],
        # GlitchTip performance/tracing support is basic — off by default; bump
        # via env if you actually use it. No profiling ingest in GlitchTip.
        traces_sample_rate=float(os.environ.get('SENTRY_TRACES_SAMPLE_RATE', '0.0')),
        profiles_sample_rate=0.0,
        # Players are identified only by an opaque X-Device-Token (no login), so
        # keep IPs/cookies/user identifiers off the wire.
        send_default_pii=False,
        environment=os.environ.get('SENTRY_ENVIRONMENT', 'production'),
        release=os.environ.get('SENTRY_RELEASE') or None,
        max_request_body_size='small',
        # Scrub this app's opaque tokens on top of Sentry's defaults (which already
        # cover Authorization/Cookie/etc.).
        event_scrubber=EventScrubber(
            denylist=DEFAULT_DENYLIST + ['x-device-token', 'x-audit-token'],
        ),
    )
