# Generated by Django 5.1.15 on 2026-07-12 13:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestionFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('index', models.PositiveIntegerField()),
                ('reason', models.TextField(blank=True)),
                ('flagged_by', models.CharField(max_length=150)),
                ('old_type', models.CharField(max_length=32)),
                ('old_payload', models.JSONField()),
                ('old_answer', models.JSONField()),
                ('regenerated', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='quiz.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flags', to='quiz.dailyquiz')),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
    ]
