# Generated by Django 5.1.15 on 2026-06-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_token', models.CharField(db_index=True, max_length=64, unique=True)),
                ('nickname', models.CharField(max_length=40)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('ads_removed', models.BooleanField(default=False)),
                ('stripe_customer_id', models.CharField(blank=True, max_length=64)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
