#!/usr/bin/env bash
#
# cf-allowlist.sh — pin the origin to Cloudflare.
#
# Fetches Cloudflare's published IP ranges and:
#   1. writes /etc/nginx/conf.d/cloudflare-realip.conf so nginx recovers the real
#      visitor IP from the CF-Connecting-IP header (otherwise every client looks
#      like a Cloudflare IP), and
#   2. rewrites the ufw allow-list so TCP/443 is reachable ONLY from Cloudflare
#      ranges — a direct hit on the origin IP is dropped.
#
# Re-runnable and idempotent (its own ufw rules are tagged 'cf-allow' and replaced
# each run). Cloudflare's ranges change rarely; re-run after they do (or wire a
# monthly systemd timer like deploy/pg-backup.timer). Run as root.
#
set -euo pipefail

REALIP_CONF=/etc/nginx/conf.d/cloudflare-realip.conf
V4_URL=https://www.cloudflare.com/ips-v4
V6_URL=https://www.cloudflare.com/ips-v6

[ "$(id -u)" -eq 0 ] || { echo "run as root" >&2; exit 1; }

# --- fetch ranges -----------------------------------------------------------
v4="$(curl -fsS "$V4_URL")"
v6="$(curl -fsS "$V6_URL")"
ranges="$(printf '%s\n%s\n' "$v4" "$v6" | grep -E '^[0-9a-fA-F:.]+/[0-9]+$' || true)"

# Refuse to proceed on a garbage/empty fetch — writing an empty allow-list would
# either lock everyone out or (worse) leave the origin wide open.
count="$(printf '%s\n' "$ranges" | grep -c . || true)"
if [ "$count" -lt 10 ]; then
  echo "refusing: only $count CIDR ranges fetched from Cloudflare (expected ~22)" >&2
  exit 1
fi
echo "fetched $count Cloudflare ranges"

# --- 1. nginx real-ip conf --------------------------------------------------
tmp="$(mktemp)"
{
  echo "# Generated by deploy/cf-allowlist.sh — do not edit by hand."
  echo "# Restores the visitor's real IP from Cloudflare's CF-Connecting-IP header."
  while IFS= read -r cidr; do
    [ -n "$cidr" ] && echo "set_real_ip_from $cidr;"
  done <<< "$ranges"
  echo "real_ip_header CF-Connecting-IP;"
} > "$tmp"
install -m 0644 "$tmp" "$REALIP_CONF"
rm -f "$tmp"
echo "wrote $REALIP_CONF"

# --- 2. ufw allow-list (443 from Cloudflare only) ---------------------------
# Drop our previous 'cf-allow' rules first. Deleting by number renumbers the
# list, so re-query the top match each iteration.
while :; do
  num="$(ufw status numbered | awk -F'[][]' '/cf-allow/ {gsub(/ /,"",$2); print $2; exit}')"
  [ -z "$num" ] && break
  yes | ufw delete "$num" >/dev/null
done

while IFS= read -r cidr; do
  [ -n "$cidr" ] && ufw allow proto tcp from "$cidr" to any port 443 comment 'cf-allow' >/dev/null
done <<< "$ranges"
echo "ufw: 443 now allowed from $count Cloudflare ranges (tagged cf-allow)"

# --- reload nginx -----------------------------------------------------------
nginx -t && systemctl reload nginx
echo "done. NOTE: ensure no world-open 'allow 80/443' ufw rule remains (only SSH + cf-allow)."
