# Generated by Django 5.1.15 on 2026-06-09 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cca2', models.CharField(max_length=2, unique=True)),
                ('cca3', models.CharField(blank=True, max_length=3)),
                ('name', models.CharField(max_length=128)),
                ('mesh_name', models.CharField(blank=True, db_index=True, max_length=128)),
                ('lat', models.FloatField(blank=True, null=True)),
                ('lng', models.FloatField(blank=True, null=True)),
                ('capital', models.CharField(blank=True, max_length=128)),
                ('capital_lat', models.FloatField(blank=True, null=True)),
                ('capital_lng', models.FloatField(blank=True, null=True)),
                ('landlocked', models.BooleanField(default=False)),
                ('independent', models.BooleanField(default=True)),
                ('region', models.CharField(blank=True, max_length=64)),
                ('subregion', models.CharField(blank=True, max_length=64)),
                ('continents', models.JSONField(default=list)),
                ('borders', models.JSONField(default=list)),
                ('flag_iso', models.CharField(blank=True, max_length=2)),
            ],
            options={
                'verbose_name_plural': 'countries',
                'ordering': ['name'],
            },
        ),
    ]
