# Generated by Django 5.1.15 on 2026-06-16 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='country',
            name='area',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
