# Generated by Django 5.1.15 on 2026-08-23 15:44

import django.db.models.deletion
from django.db import migrations, models
from django.utils.text import slugify


def backfill_slugs(apps, schema_editor):
    """Give every existing row a slug before the unique index goes on.

    Added by hand: makemigrations emits AddField with unique=True and a blank
    default, which every one of the ~250 seeded rows would take, colliding on the
    second one. Slugs derive from display_name (mesh_name when set, else name) so
    the URL matches what the globe calls the country.
    """
    Country = apps.get_model('geo', 'Country')
    seen = set()
    for country in Country.objects.all().order_by('pk'):
        base = slugify(country.mesh_name or country.name) or f'country-{country.pk}'
        slug = base
        # Distinct countries can slugify identically (e.g. accented variants).
        # Suffix rather than fail: a wrong-looking slug is fixable in admin, a
        # failed migration blocks the deploy.
        n = 2
        while slug in seen:
            slug = f'{base}-{n}'
            n += 1
        seen.add(slug)
        country.slug = slug
        country.save(update_fields=['slug'])


class Migration(migrations.Migration):

    dependencies = [
        ('geo', '0002_country_area'),
    ]

    operations = [
        # Three steps: add nullable-in-practice, fill, then constrain. Adding the
        # unique index up front would fail on the existing rows.
        migrations.AddField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, default='', max_length=140),
            preserve_default=False,
        ),
        migrations.RunPython(backfill_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='country',
            name='slug',
            field=models.SlugField(blank=True, max_length=140, unique=True),
        ),
        migrations.CreateModel(
            name='CountryContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField(blank=True)),
                ('geography', models.TextField(blank=True)),
                ('history', models.TextField(blank=True)),
                ('literature', models.TextField(blank=True)),
                ('sources', models.TextField(blank=True, help_text='One source per line: URL or citation.')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('in_review', 'In review'), ('published', 'Published')], db_index=True, default='draft', max_length=16)),
                ('reviewed_by', models.CharField(blank=True, max_length=150)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='content', to='geo.country')),
            ],
            options={
                'verbose_name_plural': 'country content',
                'ordering': ['country__name'],
            },
        ),
    ]
